[colors.primary]
background = '#222222'
foreground = '#c5c8c6'



[window]
padding={ x=5, y=0 }
blur=true
dynamic_title=false
title=""

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[terminal]
#shell={program="zellij", args=["-l", "welcome"]}
#shell={program="zsh"}
shell={program="zellij"}
[font]
size = 8

[cursor]
style= { shape="Block",blinking="Always" }
blink_interval=500
