# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = float, class:org.telegram.desktop
windowrule = size 400 600, class:org.telegram.desktop
windowrule = move 1500 460, class:org.telegram.desktop
